### ISSUE TITLE
Document generating input UV images

### ISSUE THREAD

**Issue by ScanMountGoat** [ScanMountGoat/smash_minecraft_renders#2]
This can either be the original Blender file or a description for how to generate images in the correct format.

**Comment by ScanMountGoat** [comment]
I managed to find the original Blender scenes. Rather than clean up the files for upload, I've fully documented the process in the readme. I've removed your Blender file to avoid any confusion. It will still be available from that commit in the git history if you ever need it in the future. @TheDrawingCoder-Gamer

**Comment by TheDrawingCoder-Gamer** [comment]
I'll make another PR with a more correct alex uv/lighting map

**Comment by ScanMountGoat** [comment]
If you've already achieved good results with your setup, there's no need to redo it. The render scaled down to a tiny character portrait is far more forgiving than examining the full render at 100% scaling. If you do decide that you'd like to improve any of the generated textures, you may find it easier to individually match perspective for each component like I described on the readme. I'm not sure if or when these changes will be merged into the plugin itself, so there's no rush on any of this.
